name: C/C++ CI

on:
  push:
    branches: [ "devel" ]
  pull_request:
    branches: [ "devel" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
